#!/usr/bin/bash
#plankston

logo='\033[0;46m'
a='\033[30;0m'
n='\033[0m'
h='\033[32;1m'
m='\033[31;1m'
c='\033[36;1m'
p='\033[1;35m'
k='\033[33;1m'

ls /$PREFIX/bin && sleep 2 && sh .sshprem
clear
rm -rf SSH
rm -rf .plankston
sleep 1
cp .update $HOME
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sh .plankston/.login
sh .plankston/.name0
clear
sleep 1
sh .plankston/.tamp
sh .plankston/.tamp2
sh .plankston/.tamp3
#echo $h
sh .plankston/data
sh .plankston/data2
echo $n
read -p " pilih menu : " men

case $men in
1)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/sg
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

2)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/br
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

3)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/vmesssg
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

4)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/vmessid
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

5)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/udpsg
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

6)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/udpgm
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

7)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/indo
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

8)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/singa
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

9)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/luar
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

10)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/vmess
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

11)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/claud
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

12)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
cat .plankston/udp
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

13)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
#bash $HOME/.update
#git clone https://github.com/mrben45/SSH
#mv SSH .plankston
sleep 1
echo "$h UPDATE PROGRAM [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h UPDATE PROGRAM [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
bash $HOME/.update
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

14)
echo "$h perintah benar$a"
sleep 1
#rm -rf SSH
#rm -rf .plankston
sleep 1
#xdg-open https://wa.me/6289618602219
#git clone https://github.com/mrben45/badut
#mv autossh .plankston
sleep 1
echo "$h [          ] 00% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■         ] 10% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■        ] 20% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■       ] 30% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■      ] 40% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■     ] 50% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■    ] 60% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■   ] 70% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■  ] 80% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■ ] 90% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 0.5
echo "$h [■■■■■■■■■■] 100% 𝙲𝚘𝚖𝚙𝚕𝚎𝚝𝚎𝚍"
sleep 3
#cat .plankston/udp
echo " OTOMATIS AKAN DIARAHKAN KE WHATSAPP"
sleep 1
xdg-open https://wa.me/6289618602219
sh .plankston/l
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

15)
echo "$h perintah benar$a"
sleep 1
rm -rf SSH
rm -rf .plankston
sleep 1
bash .authorBYplankston
#git clone https://github.com/mrben45/SSH
mv SSH .plankston
sleep 1
sh .plankston/menu
echo "$m tidak ada koneksi internet!"
echo ""
exit
;;

0)
echo "$m thanks😊😊😊"
echo $h
echo ""
exit
;;
*)
echo "$k perintah anda salah"
sleep 3
sh .plankston/cek
echo "$m tidak ada koneksi internet!"
echo ""
exit
esac
exit
done
